# Generated by Django 4.1.6 on 2023-02-15 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="users",
            new_name="user",
        ),
    ]
