# Generated by Django 4.1.6 on 2023-02-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_rename_users_movie_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="buyed_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
